### PR TITLE
keep table headers fixed when scrolling down

### PR DESCRIPTION
**Pull request by ancouli**
I'd like to keep the column headers visible while scrolling down the page. Do you think it is a good idea to work with sticky here?

### CODE REVIEW

**Comment by xi** [comment]
The general approach looks good. I tested it in firefox and chrome and it works mostly fine in both. However, there are still some details we might want to improve on:

1. In chrome, the table header was empty when printing the page. We could add a media query like `@media screen {` to only apply this styling on screens, not for printing.
2. Sticky headers should be avoided on screens that have limited vertical space. I am not sure whether the benefits outweigh the downsides in this case. You could try for yourself by zooming in to 400%. The solution could again be a media query, e.g. `@media (min-height: 15rem) {`.
3. In both browsers, the sticky header didn't have a bottom border. I believe this is due to some quirks with `border-collapse: collapse`. We could try avoiding it, e.g. like this:

    ```css
    table {
        border-spacing: 0;
        border-top: 1px solid black;
        border-right: 1px solid black;
    }
    td, th {
        border-bottom: 1px solid black;
        border-left: 1px solid black;
    }
    ```

    Getting rid of `border-collapse` could also have some other benefits. I believe we would no longer need `background-clip` and could make the while `thead` sticky instead of the individual `th` elements, which is more intuitive in my mind.

**Comment by xi** [comment]
The way you implemented it works, but IMHO it is a bit confusing to read. First there is styling for tables without classes, then that styling is overwritten for tables with the class `fake-td`, and then the styling is overwritten for tables inside tables with the class `fake-td`. So effectively, the default styling is not used at all (or only in very special cases). Also, it is not clear without context why tables inside `fake-td` get special treatment.

I can think of three options that would be easier to understand:

1. The default styling describes the "real" table. The "fake" tables have extra styling that overwrites the defaults.
2. The default styling describes a "regular" table. The "fake" tables have extra styling that overwrites the defaults. The sticky header is also defined separately.
3. There is no default styling for tables. Both the "real" and "fake" tables have their own styling.

I would prefer (2) over (1), but the decision between (2) and (3) for me would depend on implementation complexity.

**Comment by ancouli** [comment]
Last try: I opted for (3). The outside table is now the fake table. The nested inner table is the real table. Please feel free to make some final modifications yourself. Thank you!

Some observations (not sure if they should be added as comments in the file): 
- The sticky real thead needs to be restricted to `@media screen` otherwise there are problems with the cell borders while printing it.
- The borders of the real table need to be collapsed while printing otherwise Chrome draws a right border all over every page that contains parts of the inner real table. But if they are collapsed on screen the sticky real thead doesn't have a bottom border as noted before.

I am also not sure if the following CSS syntax with regard to the real and fake tables would be better than the one I applied:

```
.real-table,
.fake-table {
    border-spacing: 0;
}
.real-table {
    border-top: 1px solid black;
    border-right: 1px solid black;
}
```

**Comment by xi** [comment]
This approach works great! I pushed some minor changes. The biggest one was for the real table, I made the collapsed borders the default and only applied the weird border hacks when they are actually needed for the sticky header. That shouldn't change anything about the styling, but IMHO it is easier to read.

**Pull request merged**
